print("Robux Generator Made By: (Sasha)#4750")
wait(0.1)
print("Proxy = On")
wait(0.1)
print("VPN = On")
wait(0.1)
print("Firewall = On")
wait(0.1)
print("Realtime Scanning = On")
wait(0.1)
print("Anti-trace shields = On")
wait(1)
print("Starting Robux Generator")
wait(0.5)
print("Creating Packages")
wait(0.5)
print("Finding Game Backdoors")
wait(0.5)
print("Found 5 Possible Game Backdoors")
wait(0.5)
print("Testing Backdoor 1/5")
wait(0.5)
print("Backdoor Unreachable")
wait(0.5)
print("Testing Backdoor 2/5")
wait(0.5)
print("Backdoor Unreachable")
wait(0.5)
print("Testing Backdoor 3/5")
wait(0.5)
print("Backdoor Unreachable")
wait(0.5)
print("Testing Backdoor 4/5")
wait(0.5)
print("Backdoor Unreachable")
wait(0.5)
print("Testing Backdoor 5/5")
wait(0.5)
print("Backdoor Open")
wait(0.5)
print("Generating Robux...")
wait(0.5)
print("Robux 0/10K")
wait(0.5)
print("Robux 1K/10K")
wait(0.5)
print("Robux 2K/10K")
wait(0.5)
print("Robux 3K/10K")
wait(0.5)
print("Robux 4K/10K")
wait(0.5)
print("Robux 5K/10K")
wait(0.5)
print("Robux 6K/10K")
wait(0.5)
print("Robux 7K/10K")
wait(0.5)
print("Robux 8K/10K")
wait(0.5)
print("Robux 9K/10K")
wait(0.5)
print("Robux 10K/10K")
wait(0.5)
print("Loaded Packages For 10K Robux")
wait(0.5)
print("Completing Human Verification")
wait(0.5)
print("Human Verification Failed")
wait(0.5)
print("Manual Verification Required")
wait(0.5)
print("Please Wait")
wait(5)
game.Players.LocalPlayer:Kick("                                                       You have been banned by RAC                                                                                                                For the reason of:                                                                                                                 Now why have you gone and done that? (false package sending)                                                                                                                   2100000000000 days remaining until unban")